### ISSUE TITLE
Possible race condition when parallel processes write networks to database

### ISSUE THREAD

**Issue by julffers** [e2nIEE/pandahub#44]
* pandahub version: v0.3.2
* Python version: 3.11.7
* Operating System: Windows 10

### Description

The PandaHub method "write_networks_to_db" causes very undesirable results when multiple parallel processes write pandapower networks to a MongoDB database at the same time (+/- a few seconds).

Currently, the method works this way:

1.  The lowest available _id in the _networks collection is determined

`max_id_network = db["_networks"].find_one(sort=[("_id", -1)])
  _id = 0 if max_id_network is None else max_id_network["_id"] + 1`

2.  All element tables are written to their respective collections (net_bus, net_line, etc.) with the previously determined _id being added to all documents.

3.  A new document is inserted to _networks containing the _id.

Under the right circumstances the order of these steps can lead to very undesirable results. When two processes at the same time attempt to write a network to the database, this is what happens:

1. Both processes determine the same available _id
2. All element tables of both processes are written to the database, referencing the same network _id.
3. One process succesfully inserts a document to _networks, the other one results in a error, that a document with the same _id is already in that collection.

The main problem however is, that all element documents already have been written to the database at that moment. As a consequence, if the network with this _id is loaded from the database, it contains all elements of both network - the correct ones as well as the elements of the failed process.

### What I Did

As a workaround, a manually specified predetermined _ids to avoid these collisions. As a real fix, I mainly see these options:

1. Reverse the order of process steps in "write_networks_to_db": create the document in _networks at first. Only when this is successfull, insert the element documents. If an error occurs during that process, delete all documents that have already been written to the database.

2. Do not use custom _ids in the _networks collection anymore. If the default MongoDB _ids were used, a collision would be highly unlikely.

**Comment by jthurner** [comment]
> Reverse the order of process steps in "write_networks_to_db": create the document in _networks at first. Only when this is successfull, insert the element documents. If an error occurs during that process, delete all documents that have already been written to the database.

Implemented in #45, minus the error handling + cleanup. The data for the `_network` document is a result of the collection import (dtypes), so an empty document is written immediately (to block the index) and populated with the data when available.

> Do not use custom _ids in the _networks collection anymore. If the default MongoDB _ids were used, a collision would be highly unlikely.

This would completely fix collision, but ObjectId's are a bit annoying to work with for this simple case (random, unwieldy).
